#ifndef __KEYDEF_H
#define __KEYDEF_H

#define TOP "SOFTWARE\\F4LAA\\WSJTXHelper\\TOP"
#define LEFT "SOFTWARE\\F4LAA\\WSJTXHelper\\LEFT"
#define BOTTOM "SOFTWARE\\F4LAA\\WSJTXHelper\\BOTTOM"
#define RIGHT "SOFTWARE\\F4LAA\\WSJTXHelper\\RIGHT"
#define FIRST "SOFTWARE\\F4LAA\\WSJTXHelper\\FIRST"
#define ONLY1 "SOFTWARE\\F4LAA\\WSJTXHelper\\ONLY1"
#define PREVENTAUTOREPLY "SOFTWARE\\F4LAA\\WSJTXHelper\\PREVENTAUTOREPLY"
#define ENABLETXPOSX "SOFTWARE\\F4LAA\\WSJTXHelper\\ENABLETXPOSX"
#define ENABLETXPOSY "SOFTWARE\\F4LAA\\WSJTXHelper\\ENABLETXPOSY"

#endif